---
title: "Political Maps"
author: "Daniel Silva-Inclan"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    social: menu
    theme: readable
    vertical_layout: fill
---

```{r setup, include=FALSE}

require(flexdashboard)
require(shinycssloaders)
require(tidyverse)
require(shiny)

# run data prep to create pre-cached/compressed data.
# future runs will load this data which will be much faster.
# while in deveopment I've commented this out since source will change.
#if( !file.exists('source.RData') ) source( 'data-prep-flexdash.R')
source( 'data-prep-flexdash.R')
load('source.RData')

```

Sidebar {.sidebar}
================================================================================
```{r sidebar, time_it = TRUE}
tabsetPanel(type = 'tabs',
            tabPanel("test"))

```

Congress
================================================================================

Row
--------------------------------------------------------------------------------

### Score

```{r a}
```

### Congress

```{r house, timeit = TRUE}
congress_parliament_plot(congress, red)
```

Row 
--------------------------------------------------------------------------------

### US Map

```{r congress_map}
#congress_map(congress)
```

Senate
================================================================================

Row
--------------------------------------------------------------------------------

### Score

```{r senate_score}
```

### Senate

```{r senate}
#senate_parliament_plot(senate)
```

Row 
--------------------------------------------------------------------------------

### US Map

```{r senate_map}
#senate_map(senate)
```




About
================================================================================
